import {
  FaHouse,
  FaUser,
  FaCode,
  FaBriefcase,
  FaEnvelope,
  FaComment,
  FaTerminal,
  FaBars,
  FaGear,
  FaDatabase,
  FaCloudArrowUp,
  FaWindowRestore,
  FaChevronRight,
  FaComputerMouse,
  FaHtml5,
  FaCss3Alt,
  FaGitAlt,
  FaGithub,
  FaJs,
  FaFileExcel,
  FaTableCells,
  FaPlug,
  FaChartPie,
  FaRobot,
  FaRocket,
  FaFolderOpen,
  FaLocationDot,
  FaClock,
  FaPaperPlane,
  FaEnvelopeOpen,
  FaBrain,
  FaHourglassHalf,
  FaWhatsapp,
  FaLinkedinIn,
} from "react-icons/fa6";

const registry = {
  house: FaHouse,
  user: FaUser,
  code: FaCode,
  briefcase: FaBriefcase,
  envelope: FaEnvelope,
  comment: FaComment,
  terminal: FaTerminal,
  bars: FaBars,
  gear: FaGear,
  database: FaDatabase,
  cloud: FaCloudArrowUp,
  window: FaWindowRestore,
  chevronRight: FaChevronRight,
  mouse: FaComputerMouse,
  html5: FaHtml5,
  css3: FaCss3Alt,
  git: FaGitAlt,
  github: FaGithub,
  js: FaJs,
  excel: FaFileExcel,
  table: FaTableCells,
  plug: FaPlug,
  chart: FaChartPie,
  robot: FaRobot,
  rocket: FaRocket,
  "folder-open": FaFolderOpen,
  "location-dot": FaLocationDot,
  clock: FaClock,
  "paper-plane": FaPaperPlane,
  "envelope-open": FaEnvelopeOpen,
  brain: FaBrain,
  "hourglass-half": FaHourglassHalf,
  whatsapp: FaWhatsapp,
  linkedin: FaLinkedinIn,
  "table-cells": FaTableCells,
  "chart-pie": FaChartPie,
};

export default function Icon({ name, ...props }) {
  const Cmp = registry[name];
  if (!Cmp) return null;
  return <Cmp {...props} />;
}
